// TODO , ADDINGOF TWO NUMBERS  . 

function addtwonumbers(number1 , number2) { //?in THE FUNCTION WE PASS THE PARAMETERS
    console.log(number1 + number2);  //! SCOPE OF THE FUNCTION .. 
}
// ?addtwonumbers --> THIS IS ONLY THE REFERAL OF THE FUNCTION , MEANS IT TELLS THAT THE FUNCTION EXIST HERE.. 
addtwonumbers(5,5); //? CALLING OF THE FUNCTION
//? DURING THE CAALING OF THE FUNCTON WE PASS THE ARGUMENTS .. 