// PRIMITIVE DATATYPES..
// PRIMITIVE DATATYPES ARE OF 7 TYPES 
// ALL PRIMITIVE DATATYPES ARE CALL BY VALUE MEANS THERE ORIGINAL DATA IS NOT GIVEN , THE GIVEN TO THE USER IS THE COPIED DATA FORM THE MEMORY .
// STRING , NUMBER , BOOLEAN , NULL , UNDEFINED , SYMBOL , BIGINT ...

// REFERENCE DATATYPES (NON-PRIMITIVE DATATYPES) ......
// DATATYPES WHOSE REFERNCE CAN BE DIRECTLY BEEN GIVEN FROM THE MEMORY . 
// ARRAY , OBJECTS ,FUNCTIONS 

// NOTE:
// JAVASCRIPT IS DYNAMICALLY TYPED LANGUAGE BECAUSE THERE IS NO NEED TO DEFINE THE TYPE OF VARIABLES . THE TYPE OF THE VARIABLE IS DEFINED AT THE RUNTIME BASED ON THE VALUE YOU ASSIGNED TO THE VARIABLE . 

// NOTE :
// THE TYPEOF NULL IS OBJECT . 
console.log(typeof null);
