const user = {
    username : "karan",
    age : 19,
    printname(){   //? NO NEED TO WRITE THE FUNCTION BEFORE THE FUNCTION NAME BCOZZ OBJECTS ARE KEY-VALUE PAIR & FUNCTION NAME ACT AS KEY AND IT'S DEFINATION ACT AS VALUES .. 
        console.log(user.username);
    }
}
console.log(user.username);
user.printname();


//! NOW IF I HAD CHANGE THE OBJECT NAME & MULTIPLE METHODS INSIDE N OBJECT THEN WE HAVE TO CHANGE THE OBJECT NAME IN EVERY FUNCTION THEN HERE THE COMPLEXITY INCREASES , SO WE USE THE THIS KEYWORD .. 

const userdata = {
    username : "karan",
    age : 19,
    printname(){   //? NO NEED TO WRITE THE FUNCTION BEFORE THE FUNCTION NAME BCOZZ OBJECTS ARE KEY-VALUE PAIR & FUNCTION NAME ACT AS KEY AND IT'S DEFINATION ACT AS VALUES .. 
        console.log(this.username);  //! THIS KEYWORD GIVES THE REFERNCE TO THIS SIBLINGS OF THE OBJECT I.E. ALL THE DIRECT OR INDIRECT CHILDS OF OBJECTS CAN BE ACCESSED BY THIS KEYWORD IN THE PLACE OF OBJECT NAME .. 
    }
}
console.log(userdata.username);
userdata.printname();
